import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'

import NavbarComponent from "../components/Navbar"
import SkillSetComponent from '../components/SkillSet'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavbarComponent />
      <SkillSetComponent />
    </div>
  )
}
