
import React from 'react'

import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'

import NavbarComponent from "../components/Navbar"
import HeaderComponent from "../components/Header"
import SkillSetComponent from '../components/SkillSet'
import ProjectsComponent from '../components/Projects'
import ContactComponent from '../components/Contact'
import FooterComponent from '../components/Footer'

export default function Home() {
  return (
    <div className={styles.main}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavbarComponent />
      <div className={styles.pageContent}>
        <HeaderComponent />
        <hr />
        <SkillSetComponent />
        <hr />
        <ProjectsComponent />
        <hr />
        <ContactComponent />
      </div>
      <hr />
      <FooterComponent />
    </div>
  )
}
